// <auto-generated />
using System;
using AlexaBotApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlexaBotApp.Migrations
{
    [DbContext(typeof(SpeechTherapyDbContext))]
    partial class SpeechTherapyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlexaBotApp.Metrics.PhraseExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attempts");

                    b.Property<TimeSpan?>("ExerciseDuration");

                    b.Property<DateTime?>("FinishDate");

                    b.Property<bool>("IsFinished");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("TargetPhrase")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool?>("WasSuccessfull");

                    b.HasKey("Id");

                    b.ToTable("PhraseExercises","SpeechTherapy");
                });

            modelBuilder.Entity("AlexaBotApp.Metrics.Utterance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("ExerciseId");

                    b.Property<string>("RecognizedPhrase")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Utterances","SpeechTherapy");
                });

            modelBuilder.Entity("AlexaBotApp.Metrics.Utterance", b =>
                {
                    b.HasOne("AlexaBotApp.Metrics.PhraseExercise", "Exercise")
                        .WithMany("Utterances")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
